### ISSUE TITLE
takes around 4min to code it. 

### ISSUE THREAD

**Issue by loannaflip** [Kreyren/C-ping#1]
what are you doing

**Comment by Kreyren** [comment]
took 8 seconds, used for testing of a package manager for C programs

![image](https://user-images.githubusercontent.com/11302521/72683415-6976e280-3ad7-11ea-9af4-dce082c4aa59.png)

**Comment by Kreyren** [comment]
![image](https://user-images.githubusercontent.com/11302521/72683410-624fd480-3ad7-11ea-8832-b25ff9dc10de.png)

**Comment by loannaflip** [comment]
why is it seperate.

**Comment by Kreyren** [comment]
> why is it seperate.

To simulate other C lang projects for development environment without the need to resolve dependencies that will be implemented in the next stage of development

basically implementing fetching,caching, checking agains virus total assuming valid API key provided, self-hosting, p2p mirrors, mirrors in general, applying package patches if needed, package configuration, package compilation and installation in a sandbox environment with tracking for changes so that package manager knows how to undo the changes for uninstall and hooks for each phase to allow injection of code for patches directory or whatever end-user might want.
